spring:
    data:
        elasticsearch:
            cluster-nodes: "localhost:9300"
            repositories:
                enabled: true 
server:
  port: 0
#  port: ${vcap.application.port:9006}
info:
  component: ${spring.application.name}
externalconfig:
  isloaded: false
  message: none
#debug: true
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadataMap:
       instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/

logging:
    level:
        com.netflix.discovery: 'OFF'
#        com.netflix.discovery.DiscoveryClient: 'INFO'
    file: "logs/${spring.application.name}.log"
---
spring:
    profiles: docker
server:
    port: 9006
information:
    activeprofile: docker
eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadataMap:
       instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://demodiscovery:8761/eureka/
logging:
    level:
        com.netflix.discovery.DiscoveryClient: 'INFO'
#        com.netflix.discovery: 'OFF'
    file: "tmp/logs/${spring.application.name}.log"
